name: CD - Terraform Deploy Strapi

# Manual trigger
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPO: ${{ secrets.ECR_REPO }}
      IMAGE_TAG: ${{ github.event.inputs.image_tag }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Terraform Init
      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        working-directory: ./Terraform
        run: terraform plan -var="image_name=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}" -var="image_tag=${{ env.IMAGE_TAG }}" -var="aws_region=${{ env.AWS_REGION }}"

      # Step 5: Terraform Apply
      - name: Terraform Apply
        working-directory: ./Terraform
        run: terraform apply -auto-approve -var="image_name=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}" -var="image_tag=${{ env.IMAGE_TAG }}" -var="aws_region=${{ env.AWS_REGION }}"
